version: "2.3"
services:
  dev:
    runtime: nvidia
    build:
      context: .
      dockerfile: ./docker/Dockerfile
      args:
        PYTHON_VERSION: 3.9
        TORCH_VERSION: 2.0.1+cu117
        TORCHVISION_VERSION: 0.15.2
        TORCH_CUDA_ARCH_LIST: 7.5;8.0;8.6
        MIM_VERSION: 0.3.3
        MMCV_VERSION: 1.7.0
        MMDET_VERSION: 2.28.0
        WANDB_VERSION: 0.16.4 
    shm_size: "16gb"
    tty: true
    volumes:
      - .:/work
      - $HOME/dataset:/work/dataset
